### ISSUE TITLE
Add a declarative way to define controllers

### ISSUE THREAD

**Issue by ben-ryder** [kangojs/kangojs#7]
**Package Information:** kangojs, all versions

**Describe your feature**
Add a declarative way to define controllers, which means that rather than solely relying on file globbing to find and load them you could simply pass a list of controllers when instanciating or bootstrapping KangoJS.

**Is your suggestion related to any problems?**
Application startup feels quite slow when using KangoJS. I think this might be because of how long it takes for the file globbing to work. If controller classes could directly be passed to KangoJS this might speed up start times.

**Additional context**
It would be intresting to measure how long start times take before and after this feature is added. If it actually doesn't make much of a difference then it might not be worth adding the feature.

This feature would also introduce multiple ways of doing the same thing, it might be best to just pick one?

**Comment by Ben-Ryder** [comment]
**Benchmark with file glob**
`npm run develop` time to server start about 4.7 seconds

**Benchmark with declarative controllers**
`npm run develop` time to server start about ?? seconds
